namespace qbPortWeaver;

partial class MediaManagerForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _operationCts?.Cancel();
            _operationCts?.Dispose();
            _thumbnailCts?.Cancel();
            _thumbnailCts?.Dispose();
            lblTmdbTitle?.Font?.Dispose();
            components?.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components       = new System.ComponentModel.Container();
        toolTip          = new ToolTip(components);
        grpGeneral       = new GroupBox();
        chkEnabled       = new CheckBox();
        lblTmdbApiKey    = new Label();
        txtTmdbApiKey    = new TextBox();
        chkDryRun        = new CheckBox();
        chkCreateFolders      = new CheckBox();
        chkDeleteEmptyFolders = new CheckBox();
        lblImportMode         = new Label();
        cboImportMode         = new ComboBox();
        grpLibrary                 = new GroupBox();
        lblMoviesLibraryPath       = new Label();
        txtMoviesLibraryPath       = new TextBox();
        btnBrowseMoviesLibrary     = new Button();
        lblTvShowsLibraryPath      = new Label();
        txtTvShowsLibraryPath      = new TextBox();
        btnBrowseTvShowsLibrary    = new Button();
        grpSourceFolders      = new GroupBox();
        lstSourceFolders      = new ListBox();
        btnAddSourceFolder    = new Button();
        btnRemoveSourceFolder = new Button();
        btnScanNow        = new Button();
        btnImportNow      = new Button();
        btnClearCache     = new Button();
        btnRematch        = new Button();
        lblScanStatus       = new Label();
        chkShowOnlyReview   = new CheckBox();
        lblLegendUncertain  = new Label();
        lblLegendUnmatched  = new Label();
        prgScan        = new ProgressBar();
        dgvResults     = new DataGridView();
        colInclude     = new DataGridViewCheckBoxColumn();
        colType        = new DataGridViewTextBoxColumn();
        colCurrent     = new DataGridViewTextBoxColumn();
        colProposed    = new DataGridViewTextBoxColumn();
        pnlTmdbDetail     = new Panel();
        picTmdbPoster     = new PictureBox();
        lblTmdbTitle      = new Label();
        lblTmdbMeta       = new Label();
        lblTmdbConfidence = new Label();
        rtbTmdbOverview   = new RichTextBox();
        btnOK          = new Button();
        btnCancel      = new Button();
        grpGeneral.SuspendLayout();
        grpLibrary.SuspendLayout();
        grpSourceFolders.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)dgvResults).BeginInit();
        pnlTmdbDetail.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)picTmdbPoster).BeginInit();
        SuspendLayout();
        // ── grpGeneral ────────────────────────────────────────────────
        grpGeneral.Controls.Add(chkEnabled);
        grpGeneral.Controls.Add(lblTmdbApiKey);
        grpGeneral.Controls.Add(txtTmdbApiKey);
        grpGeneral.Controls.Add(chkDryRun);
        grpGeneral.Controls.Add(chkCreateFolders);
        grpGeneral.Controls.Add(chkDeleteEmptyFolders);
        grpGeneral.Controls.Add(lblImportMode);
        grpGeneral.Controls.Add(cboImportMode);
        grpGeneral.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        grpGeneral.Location = new Point(8, 8);
        grpGeneral.Name     = "grpGeneral";
        grpGeneral.Size     = new Size(684, 204);
        grpGeneral.TabIndex = 0;
        grpGeneral.TabStop  = false;
        grpGeneral.Text     = "General";
        chkEnabled.AutoSize = true;
        chkEnabled.Location = new Point(15, 24);
        chkEnabled.Name     = "chkEnabled";
        chkEnabled.TabIndex = 0;
        chkEnabled.Text     = "Enable Media Manager";
        lblTmdbApiKey.Location  = new Point(12, 53);
        lblTmdbApiKey.Name      = "lblTmdbApiKey";
        lblTmdbApiKey.Size      = new Size(130, 23);
        lblTmdbApiKey.TabIndex  = 1;
        lblTmdbApiKey.Text      = "TMDB API Key:";
        lblTmdbApiKey.TextAlign = ContentAlignment.MiddleLeft;
        txtTmdbApiKey.Anchor       = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtTmdbApiKey.Location     = new Point(148, 53);
        txtTmdbApiKey.Name         = "txtTmdbApiKey";
        txtTmdbApiKey.PasswordChar = '*';
        txtTmdbApiKey.Size         = new Size(524, 23);
        txtTmdbApiKey.TabIndex     = 2;
        chkDryRun.AutoSize = true;
        chkDryRun.Location = new Point(15, 82);
        chkDryRun.Name     = "chkDryRun";
        chkDryRun.TabIndex = 3;
        chkDryRun.Text     = "Dry run (preview only - no files will be imported)";
        chkCreateFolders.AutoSize = true;
        chkCreateFolders.Location = new Point(15, 111);
        chkCreateFolders.Name     = "chkCreateFolders";
        chkCreateFolders.TabIndex = 4;
        chkCreateFolders.Text     = "Create Plex folder structure when importing";
        chkDeleteEmptyFolders.AutoSize = true;
        chkDeleteEmptyFolders.Location = new Point(15, 140);
        chkDeleteEmptyFolders.Name     = "chkDeleteEmptyFolders";
        chkDeleteEmptyFolders.TabIndex = 5;
        chkDeleteEmptyFolders.Text     = "Delete empty source folders after importing (folders with only .nfo files are also removed)";
        lblImportMode.Location  = new Point(12, 169);
        lblImportMode.Name      = "lblImportMode";
        lblImportMode.Size      = new Size(130, 23);
        lblImportMode.TabIndex  = 6;
        lblImportMode.Text      = "Import mode:";
        lblImportMode.TextAlign = ContentAlignment.MiddleLeft;
        cboImportMode.DropDownStyle = ComboBoxStyle.DropDownList;
        cboImportMode.Items.AddRange(new object[] { "Hardlink", "Copy", "Move" });
        cboImportMode.Location = new Point(148, 169);
        cboImportMode.Name     = "cboImportMode";
        cboImportMode.Size     = new Size(120, 23);
        cboImportMode.TabIndex = 7;
        // ── grpLibrary ────────────────────────────────────────────────
        grpLibrary.Controls.Add(lblMoviesLibraryPath);
        grpLibrary.Controls.Add(txtMoviesLibraryPath);
        grpLibrary.Controls.Add(btnBrowseMoviesLibrary);
        grpLibrary.Controls.Add(lblTvShowsLibraryPath);
        grpLibrary.Controls.Add(txtTvShowsLibraryPath);
        grpLibrary.Controls.Add(btnBrowseTvShowsLibrary);
        grpLibrary.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        grpLibrary.Location = new Point(8, 220);
        grpLibrary.Name     = "grpLibrary";
        grpLibrary.Size     = new Size(684, 88);
        grpLibrary.TabIndex = 1;
        grpLibrary.TabStop  = false;
        grpLibrary.Text     = "Library Folders";
        lblMoviesLibraryPath.Location  = new Point(12, 24);
        lblMoviesLibraryPath.Name      = "lblMoviesLibraryPath";
        lblMoviesLibraryPath.Size      = new Size(130, 23);
        lblMoviesLibraryPath.TabIndex  = 0;
        lblMoviesLibraryPath.Text      = "Movies library:";
        lblMoviesLibraryPath.TextAlign = ContentAlignment.MiddleLeft;
        txtMoviesLibraryPath.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtMoviesLibraryPath.Location = new Point(148, 24);
        txtMoviesLibraryPath.Name     = "txtMoviesLibraryPath";
        txtMoviesLibraryPath.Size     = new Size(480, 23);
        txtMoviesLibraryPath.TabIndex = 1;
        btnBrowseMoviesLibrary.Anchor   = AnchorStyles.Top | AnchorStyles.Right;
        btnBrowseMoviesLibrary.Location = new Point(634, 24);
        btnBrowseMoviesLibrary.Name     = "btnBrowseMoviesLibrary";
        btnBrowseMoviesLibrary.Size     = new Size(40, 23);
        btnBrowseMoviesLibrary.TabIndex = 2;
        btnBrowseMoviesLibrary.Text     = "...";
        btnBrowseMoviesLibrary.Click   += btnBrowseMoviesLibrary_Click;
        lblTvShowsLibraryPath.Location  = new Point(12, 53);
        lblTvShowsLibraryPath.Name      = "lblTvShowsLibraryPath";
        lblTvShowsLibraryPath.Size      = new Size(130, 23);
        lblTvShowsLibraryPath.TabIndex  = 3;
        lblTvShowsLibraryPath.Text      = "TV shows library:";
        lblTvShowsLibraryPath.TextAlign = ContentAlignment.MiddleLeft;
        txtTvShowsLibraryPath.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        txtTvShowsLibraryPath.Location = new Point(148, 53);
        txtTvShowsLibraryPath.Name     = "txtTvShowsLibraryPath";
        txtTvShowsLibraryPath.Size     = new Size(480, 23);
        txtTvShowsLibraryPath.TabIndex = 4;
        btnBrowseTvShowsLibrary.Anchor   = AnchorStyles.Top | AnchorStyles.Right;
        btnBrowseTvShowsLibrary.Location = new Point(634, 53);
        btnBrowseTvShowsLibrary.Name     = "btnBrowseTvShowsLibrary";
        btnBrowseTvShowsLibrary.Size     = new Size(40, 23);
        btnBrowseTvShowsLibrary.TabIndex = 5;
        btnBrowseTvShowsLibrary.Text     = "...";
        btnBrowseTvShowsLibrary.Click   += btnBrowseTvShowsLibrary_Click;
        // ── grpSourceFolders ──────────────────────────────────────────
        grpSourceFolders.Controls.Add(lstSourceFolders);
        grpSourceFolders.Controls.Add(btnAddSourceFolder);
        grpSourceFolders.Controls.Add(btnRemoveSourceFolder);
        grpSourceFolders.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        grpSourceFolders.Location = new Point(8, 316);
        grpSourceFolders.Name     = "grpSourceFolders";
        grpSourceFolders.Size     = new Size(684, 119);
        grpSourceFolders.TabIndex = 2;
        grpSourceFolders.TabStop  = false;
        grpSourceFolders.Text     = "Source Folders";
        lstSourceFolders.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        lstSourceFolders.Location = new Point(12, 24);
        lstSourceFolders.Name     = "lstSourceFolders";
        lstSourceFolders.Size     = new Size(660, 56);
        lstSourceFolders.TabIndex = 0;
        btnAddSourceFolder.Anchor   = AnchorStyles.Bottom | AnchorStyles.Left;
        btnAddSourceFolder.Location = new Point(12, 84);
        btnAddSourceFolder.Name     = "btnAddSourceFolder";
        btnAddSourceFolder.Size     = new Size(75, 23);
        btnAddSourceFolder.TabIndex = 1;
        btnAddSourceFolder.Text     = "Add...";
        btnAddSourceFolder.Click   += btnAddSourceFolder_Click;
        btnRemoveSourceFolder.Anchor   = AnchorStyles.Bottom | AnchorStyles.Left;
        btnRemoveSourceFolder.Location = new Point(92, 84);
        btnRemoveSourceFolder.Name     = "btnRemoveSourceFolder";
        btnRemoveSourceFolder.Size     = new Size(75, 23);
        btnRemoveSourceFolder.TabIndex = 2;
        btnRemoveSourceFolder.Text     = "Remove";
        btnRemoveSourceFolder.Click   += btnRemoveSourceFolder_Click;
        // ── Action buttons ────────────────────────────────────────────
        btnScanNow.Location = new Point(8, 443);
        btnScanNow.Name     = "btnScanNow";
        btnScanNow.Size     = new Size(90, 28);
        btnScanNow.TabIndex = 3;
        btnScanNow.Text     = "Scan Now";
        btnScanNow.Click   += btnScanNow_Click;
        btnImportNow.Enabled  = false;
        btnImportNow.Location = new Point(106, 443);
        btnImportNow.Name     = "btnImportNow";
        btnImportNow.Size     = new Size(100, 28);
        btnImportNow.TabIndex = 4;
        btnImportNow.Text     = "Import Now";
        btnImportNow.Click   += btnImportNow_Click;
        btnClearCache.Location = new Point(214, 443);
        btnClearCache.Name     = "btnClearCache";
        btnClearCache.Size     = new Size(100, 28);
        btnClearCache.TabIndex = 5;
        btnClearCache.Text     = "Clear Cache";
        btnClearCache.Click   += btnClearCache_Click;
        btnRematch.Location = new Point(322, 443);
        btnRematch.Name     = "btnRematch";
        btnRematch.Size     = new Size(90, 28);
        btnRematch.TabIndex = 6;
        btnRematch.Text     = "Re-match";
        btnRematch.Click   += btnRematch_Click;
        lblScanStatus.Anchor    = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        lblScanStatus.Location  = new Point(420, 443);
        lblScanStatus.Name      = "lblScanStatus";
        lblScanStatus.Size      = new Size(272, 28);
        lblScanStatus.TabIndex  = 7;
        lblScanStatus.TextAlign = ContentAlignment.MiddleLeft;
        lblScanStatus.ForeColor = SystemColors.GrayText;
        // ── Results grid ──────────────────────────────────────────────
        chkShowOnlyReview.Anchor   = AnchorStyles.Bottom | AnchorStyles.Left;
        chkShowOnlyReview.Location = new Point(8, 692);
        chkShowOnlyReview.Name     = "chkShowOnlyReview";
        chkShowOnlyReview.AutoSize = true;
        chkShowOnlyReview.TabIndex = 10;
        chkShowOnlyReview.Text     = "Show only rows with uncertain or no TMDB match";
        chkShowOnlyReview.CheckedChanged += chkShowOnlyReview_CheckedChanged;
        lblLegendUncertain.Anchor    = AnchorStyles.Bottom | AnchorStyles.Right;
        lblLegendUncertain.Location  = new Point(438, 692);
        lblLegendUncertain.Name      = "lblLegendUncertain";
        lblLegendUncertain.Size      = new Size(130, 20);
        lblLegendUncertain.TextAlign = ContentAlignment.MiddleRight;
        lblLegendUncertain.TabIndex  = 11;
        lblLegendUncertain.Text      = "\u25cf Uncertain TMDB";
        lblLegendUnmatched.Anchor    = AnchorStyles.Bottom | AnchorStyles.Right;
        lblLegendUnmatched.Location  = new Point(572, 692);
        lblLegendUnmatched.Name      = "lblLegendUnmatched";
        lblLegendUnmatched.Size      = new Size(120, 20);
        lblLegendUnmatched.TextAlign = ContentAlignment.MiddleRight;
        lblLegendUnmatched.TabIndex  = 12;
        lblLegendUnmatched.Text      = "\u25cf No TMDB match";
        prgScan.Anchor   = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        prgScan.Location = new Point(8, 475);
        prgScan.Name     = "prgScan";
        prgScan.Size     = new Size(684, 16);
        prgScan.TabIndex = 8;
        prgScan.Visible  = false;
        dgvResults.AllowUserToAddRows    = false;
        dgvResults.AllowUserToDeleteRows = false;
        dgvResults.AllowUserToResizeRows = false;
        dgvResults.AutoSizeColumnsMode   = DataGridViewAutoSizeColumnsMode.Fill;
        dgvResults.BackgroundColor       = SystemColors.Window;
        dgvResults.BorderStyle           = BorderStyle.Fixed3D;
        dgvResults.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        dgvResults.Columns.AddRange(colInclude, colType, colCurrent, colProposed);
        dgvResults.Anchor       = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right | AnchorStyles.Bottom;
        dgvResults.Location     = new Point(8, 493);
        dgvResults.Name         = "dgvResults";
        dgvResults.RowHeadersVisible = false;
        dgvResults.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        dgvResults.Size         = new Size(684, 196);
        dgvResults.ClipboardCopyMode = DataGridViewClipboardCopyMode.EnableWithoutHeaderText;
        dgvResults.TabIndex          = 9;
        dgvResults.TabStop           = false;
        dgvResults.CellFormatting          += dgvResults_CellFormatting;
        dgvResults.CellContentClick        += dgvResults_CellContentClick;
        dgvResults.CellEndEdit             += dgvResults_CellEndEdit;
        dgvResults.ColumnHeaderMouseClick  += dgvResults_ColumnHeaderMouseClick;
        dgvResults.KeyDown                 += dgvResults_KeyDown;
        dgvResults.SelectionChanged        += dgvResults_SelectionChanged;
        colInclude.FillWeight   = 5;
        colInclude.HeaderText   = "";
        colInclude.MinimumWidth = 30;
        colInclude.Name         = "colInclude";
        colInclude.SortMode     = DataGridViewColumnSortMode.NotSortable;
        colType.FillWeight    = 12;
        colType.HeaderText    = "Type";
        colType.MinimumWidth  = 50;
        colType.Name          = "colType";
        colType.ReadOnly      = true;
        colType.SortMode      = DataGridViewColumnSortMode.Automatic;
        colCurrent.FillWeight   = 44;
        colCurrent.HeaderText   = "Current";
        colCurrent.MinimumWidth = 100;
        colCurrent.Name         = "colCurrent";
        colCurrent.ReadOnly     = true;
        colCurrent.SortMode     = DataGridViewColumnSortMode.Automatic;
        colProposed.FillWeight   = 44;
        colProposed.HeaderText   = "Proposed";
        colProposed.MinimumWidth = 100;
        colProposed.Name         = "colProposed";
        colProposed.SortMode     = DataGridViewColumnSortMode.Automatic;
        // ── TMDB detail panel ─────────────────────────────────────────
        pnlTmdbDetail.Controls.Add(picTmdbPoster);
        pnlTmdbDetail.Controls.Add(lblTmdbTitle);
        pnlTmdbDetail.Controls.Add(lblTmdbMeta);
        pnlTmdbDetail.Controls.Add(lblTmdbConfidence);
        pnlTmdbDetail.Controls.Add(rtbTmdbOverview);
        pnlTmdbDetail.Anchor      = AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        pnlTmdbDetail.BorderStyle = BorderStyle.FixedSingle;
        pnlTmdbDetail.Location    = new Point(8, 719);
        pnlTmdbDetail.Name        = "pnlTmdbDetail";
        pnlTmdbDetail.Size        = new Size(684, 136);
        pnlTmdbDetail.TabIndex    = 13;
        picTmdbPoster.Location    = new Point(8, 8);
        picTmdbPoster.Name        = "picTmdbPoster";
        picTmdbPoster.Size        = new Size(67, 94);
        picTmdbPoster.SizeMode    = PictureBoxSizeMode.Zoom;
        picTmdbPoster.TabIndex    = 0;
        picTmdbPoster.TabStop     = false;
        picTmdbPoster.Visible     = false;
        lblTmdbTitle.Anchor       = AnchorStyles.Top | AnchorStyles.Left;
        lblTmdbTitle.Font         = new System.Drawing.Font(Font.FontFamily, Font.Size, System.Drawing.FontStyle.Bold);
        lblTmdbTitle.Location     = new Point(84, 10);
        lblTmdbTitle.Name         = "lblTmdbTitle";
        lblTmdbTitle.Size         = new Size(390, 20);
        lblTmdbTitle.TabIndex     = 1;
        lblTmdbMeta.Anchor        = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        lblTmdbMeta.Location      = new Point(84, 36);
        lblTmdbMeta.Name          = "lblTmdbMeta";
        lblTmdbMeta.Size          = new Size(590, 18);
        lblTmdbMeta.TabIndex      = 2;
        lblTmdbMeta.ForeColor     = SystemColors.GrayText;
        lblTmdbConfidence.Anchor  = AnchorStyles.Top | AnchorStyles.Right;
        lblTmdbConfidence.Location = new Point(480, 10);
        lblTmdbConfidence.Name    = "lblTmdbConfidence";
        lblTmdbConfidence.Size    = new Size(190, 20);
        lblTmdbConfidence.TabIndex = 3;
        lblTmdbConfidence.TextAlign = ContentAlignment.MiddleRight;
        rtbTmdbOverview.Anchor    = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        rtbTmdbOverview.BackColor = SystemColors.Control;
        rtbTmdbOverview.BorderStyle = BorderStyle.None;
        rtbTmdbOverview.Location  = new Point(84, 58);
        rtbTmdbOverview.Name      = "rtbTmdbOverview";
        rtbTmdbOverview.ReadOnly  = true;
        rtbTmdbOverview.ScrollBars = RichTextBoxScrollBars.Vertical;
        rtbTmdbOverview.Size      = new Size(590, 70);
        rtbTmdbOverview.TabIndex  = 4;
        rtbTmdbOverview.TabStop   = false;
        // ── Buttons ───────────────────────────────────────────────────
        btnOK.Anchor   = AnchorStyles.Bottom | AnchorStyles.Right;
        btnOK.Location = new Point(520, 862);
        btnOK.Name     = "btnOK";
        btnOK.Size     = new Size(82, 28);
        btnOK.TabIndex = 14;
        btnOK.Text     = "OK";
        btnOK.Click   += btnOK_Click;
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Anchor       = AnchorStyles.Bottom | AnchorStyles.Right;
        btnCancel.Location     = new Point(610, 862);
        btnCancel.Name         = "btnCancel";
        btnCancel.Size         = new Size(82, 28);
        btnCancel.TabIndex     = 15;
        btnCancel.Text         = "Cancel";
        btnCancel.Click       += btnCancel_Click;
        // ── MediaManagerForm ──────────────────────────────────────────
        AcceptButton        = btnOK;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode       = AutoScaleMode.Font;
        CancelButton        = btnCancel;
        ClientSize          = new Size(700, 898);
        Controls.Add(grpGeneral);
        Controls.Add(grpLibrary);
        Controls.Add(grpSourceFolders);
        Controls.Add(btnScanNow);
        Controls.Add(btnImportNow);
        Controls.Add(btnClearCache);
        Controls.Add(btnRematch);
        Controls.Add(lblScanStatus);
        Controls.Add(chkShowOnlyReview);
        Controls.Add(lblLegendUncertain);
        Controls.Add(lblLegendUnmatched);
        Controls.Add(prgScan);
        Controls.Add(dgvResults);
        Controls.Add(pnlTmdbDetail);
        Controls.Add(btnOK);
        Controls.Add(btnCancel);
        FormBorderStyle = FormBorderStyle.Sizable;
        MaximizeBox     = true;
        MinimizeBox     = true;
        // MinimumSize is set at runtime in OnLoad (= initial Size) so the bottom-anchored grid and
        // detail panel are never clipped; a static designer value here would be overridden anyway.
        Name            = "MediaManagerForm";
        Icon            = Properties.Resources.qbPortWeaver;
        ShowIcon        = true;
        ShowInTaskbar   = true;
        StartPosition   = FormStartPosition.CenterScreen;
        Text            = "qbPortWeaver | Media Manager";
        grpGeneral.ResumeLayout(false);
        grpGeneral.PerformLayout();
        grpLibrary.ResumeLayout(false);
        grpLibrary.PerformLayout();
        grpSourceFolders.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)dgvResults).EndInit();
        pnlTmdbDetail.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)picTmdbPoster).EndInit();
        ResumeLayout(false);
    }

    private GroupBox grpGeneral;
    private CheckBox chkEnabled;
    private Label    lblTmdbApiKey;
    private TextBox  txtTmdbApiKey;
    private CheckBox chkDryRun;
    private CheckBox chkCreateFolders;
    private CheckBox chkDeleteEmptyFolders;
    private Label    lblImportMode;
    private ComboBox cboImportMode;

    private GroupBox grpLibrary;
    private Label    lblMoviesLibraryPath;
    private TextBox  txtMoviesLibraryPath;
    private Button   btnBrowseMoviesLibrary;
    private Label    lblTvShowsLibraryPath;
    private TextBox  txtTvShowsLibraryPath;
    private Button   btnBrowseTvShowsLibrary;

    private GroupBox grpSourceFolders;
    private ListBox  lstSourceFolders;
    private Button   btnAddSourceFolder;
    private Button   btnRemoveSourceFolder;

    private ProgressBar      prgScan;
    private Button           btnScanNow;
    private Button           btnImportNow;
    private Button           btnClearCache;
    private Button           btnRematch;
    private Label            lblScanStatus;
    private CheckBox         chkShowOnlyReview;
    private Label            lblLegendUncertain;
    private Label            lblLegendUnmatched;
    private DataGridView     dgvResults;
    private DataGridViewCheckBoxColumn colInclude;
    private DataGridViewTextBoxColumn colType;
    private DataGridViewTextBoxColumn colCurrent;
    private DataGridViewTextBoxColumn colProposed;

    private Panel       pnlTmdbDetail;
    private PictureBox  picTmdbPoster;
    private Label       lblTmdbTitle;
    private Label       lblTmdbMeta;
    private Label       lblTmdbConfidence;
    private RichTextBox rtbTmdbOverview;

    private Button btnOK;
    private Button btnCancel;

    private ToolTip toolTip;
}
