namespace qbPortWeaver;

partial class SettingsForm
{
    private System.ComponentModel.IContainer components = null;

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            components?.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        tabSettings               = new TabControl();
        tabGeneral                = new TabPage();
        tabClient                 = new TabPage();
        tabExtra                  = new TabPage();
        grpGeneral                = new GroupBox();
        lblVpnProvider            = new Label();
        cboVpnProvider            = new ComboBox();
        lblBitTorrentClient       = new Label();
        cboBitTorrentClient       = new ComboBox();
        lblUpdateInterval         = new Label();
        nudUpdateInterval         = new NumericUpDown();
        lblSeconds                = new Label();
        lblNatPmpAdapter          = new Label();
        cboNatPmpAdapter          = new ComboBox();
        btnRefreshAdapters        = new Button();
        grpAutoRecovery           = new GroupBox();
        chkAutoRecovery           = new CheckBox();
        lblRecoveryCycles         = new Label();
        nudRecoveryCycles         = new NumericUpDown();
        lblRecoveryCyclesUnit     = new Label();
        chkPortClosedRecovery     = new CheckBox();
        lblPortClosedCycles       = new Label();
        nudPortClosedCycles       = new NumericUpDown();
        lblPortClosedCyclesUnit   = new Label();
        chkVerifyPort             = new CheckBox();
        chkNotifyOnPortUpdate     = new CheckBox();
        chkShowUpdateForm         = new CheckBox();
        grpQBittorrent            = new GroupBox();
        lblQBittorrentURL         = new Label();
        txtQBittorrentURL         = new TextBox();
        lblQBittorrentUserName    = new Label();
        txtQBittorrentUserName    = new TextBox();
        lblQBittorrentPassword    = new Label();
        txtQBittorrentPassword    = new TextBox();
        lblQBittorrentExePath     = new Label();
        txtQBittorrentExePath     = new TextBox();
        btnBrowseExePath          = new Button();
        btnTestQBittorrent        = new Button();
        lblQBittorrentProcessName = new Label();
        txtQBittorrentProcessName = new TextBox();
        chkRestartQBittorrent     = new CheckBox();
        chkForceStartQBittorrent  = new CheckBox();
        lblDefaultPort            = new Label();
        nudDefaultPort            = new NumericUpDown();
        chkWarnOnInterfaceMismatch = new CheckBox();
        chkRestartOnDisconnect    = new CheckBox();
        grpDeluge               = new GroupBox();
        lblDelugeURL            = new Label();
        txtDelugeURL            = new TextBox();
        lblDelugePassword       = new Label();
        txtDelugePassword       = new TextBox();
        lblDelugeExePath        = new Label();
        txtDelugeExePath        = new TextBox();
        btnBrowseDelugeExePath  = new Button();
        btnTestDeluge           = new Button();
        lblDelugeProcessName    = new Label();
        txtDelugeProcessName    = new TextBox();
        chkRestartDeluge        = new CheckBox();
        chkForceStartDeluge     = new CheckBox();
        lblDelugeDefaultPort    = new Label();
        nudDelugeDefaultPort    = new NumericUpDown();
        grpTransmission               = new GroupBox();
        lblTransmissionURL            = new Label();
        txtTransmissionURL            = new TextBox();
        lblTransmissionUserName       = new Label();
        txtTransmissionUserName       = new TextBox();
        lblTransmissionPassword       = new Label();
        txtTransmissionPassword       = new TextBox();
        lblTransmissionProcessName    = new Label();
        txtTransmissionProcessName    = new TextBox();
        lblTransmissionExePath        = new Label();
        txtTransmissionExePath        = new TextBox();
        btnBrowseTransmissionExePath  = new Button();
        btnTestTransmission           = new Button();
        chkRestartTransmission        = new CheckBox();
        chkForceStartTransmission     = new CheckBox();
        lblTransmissionDefaultPort    = new Label();
        nudTransmissionDefaultPort    = new NumericUpDown();
        grpExtra             = new GroupBox();
        lblColorTheme        = new Label();
        cboColorTheme        = new ComboBox();
        lblPostUpdateCmd     = new Label();
        txtPostUpdateCmd     = new TextBox();
        chkDebugMode         = new CheckBox();
        btnOK                = new Button();
        btnCancel            = new Button();
        toolTip              = new ToolTip(components);
        tabSettings.SuspendLayout();
        tabGeneral.SuspendLayout();
        tabClient.SuspendLayout();
        tabExtra.SuspendLayout();
        grpGeneral.SuspendLayout();
        grpAutoRecovery.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudUpdateInterval).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudRecoveryCycles).BeginInit();
        ((System.ComponentModel.ISupportInitialize)nudPortClosedCycles).BeginInit();
        grpQBittorrent.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudDefaultPort).BeginInit();
        grpDeluge.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudDelugeDefaultPort).BeginInit();
        grpTransmission.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)nudTransmissionDefaultPort).BeginInit();
        grpExtra.SuspendLayout();
        SuspendLayout();
        // ── grpGeneral ────────────────────────────────────────────────
        grpGeneral.Controls.Add(lblBitTorrentClient);
        grpGeneral.Controls.Add(cboBitTorrentClient);
        grpGeneral.Controls.Add(lblUpdateInterval);
        grpGeneral.Controls.Add(nudUpdateInterval);
        grpGeneral.Controls.Add(lblSeconds);
        grpGeneral.Controls.Add(lblVpnProvider);
        grpGeneral.Controls.Add(cboVpnProvider);
        grpGeneral.Controls.Add(lblNatPmpAdapter);
        grpGeneral.Controls.Add(cboNatPmpAdapter);
        grpGeneral.Controls.Add(btnRefreshAdapters);
        grpGeneral.Controls.Add(chkNotifyOnPortUpdate);
        grpGeneral.Controls.Add(chkShowUpdateForm);
        grpGeneral.Controls.Add(grpAutoRecovery);
        // All five group boxes share one size that fills the tab page with an even margin,
        // so every tab shows an identical frame regardless of how much content it holds.
        grpGeneral.Location = new Point(6, 6);
        grpGeneral.Name     = "grpGeneral";
        grpGeneral.Size     = new Size(488, 352);
        grpGeneral.TabIndex = 0;
        grpGeneral.TabStop  = false;
        grpGeneral.Text     = "General";
        lblBitTorrentClient.Location  = new Point(12, 24);
        lblBitTorrentClient.Name      = "lblBitTorrentClient";
        lblBitTorrentClient.Size      = new Size(130, 23);
        lblBitTorrentClient.TabIndex  = 0;
        lblBitTorrentClient.Text      = "Client:";
        lblBitTorrentClient.TextAlign = ContentAlignment.MiddleLeft;
        cboBitTorrentClient.DropDownStyle        = ComboBoxStyle.DropDownList;
        cboBitTorrentClient.Location             = new Point(148, 24);
        cboBitTorrentClient.Name                 = "cboBitTorrentClient";
        cboBitTorrentClient.Size                 = new Size(200, 23);
        cboBitTorrentClient.TabIndex             = 1;
        cboBitTorrentClient.SelectedIndexChanged += cboBitTorrentClient_SelectedIndexChanged;
        lblUpdateInterval.Location  = new Point(12, 53);
        lblUpdateInterval.Name      = "lblUpdateInterval";
        lblUpdateInterval.Size      = new Size(130, 23);
        lblUpdateInterval.TabIndex  = 2;
        lblUpdateInterval.Text      = "Update interval:";
        lblUpdateInterval.TextAlign = ContentAlignment.MiddleLeft;
        nudUpdateInterval.Location = new Point(148, 53);
        nudUpdateInterval.Maximum  = new decimal(new int[] { 86400, 0, 0, 0 });
        nudUpdateInterval.Minimum  = new decimal(new int[] { 10, 0, 0, 0 });
        nudUpdateInterval.Name     = "nudUpdateInterval";
        nudUpdateInterval.Size     = new Size(80, 23);
        nudUpdateInterval.TabIndex = 3;
        nudUpdateInterval.Value    = new decimal(new int[] { 180, 0, 0, 0 });
        lblSeconds.Location  = new Point(234, 53);
        lblSeconds.Name      = "lblSeconds";
        lblSeconds.Size      = new Size(55, 23);
        lblSeconds.TabIndex  = 4;
        lblSeconds.Text      = "seconds";
        lblSeconds.TextAlign = ContentAlignment.MiddleLeft;
        lblVpnProvider.Location  = new Point(12, 82);
        lblVpnProvider.Name      = "lblVpnProvider";
        lblVpnProvider.Size      = new Size(130, 23);
        lblVpnProvider.TabIndex  = 5;
        lblVpnProvider.Text      = "VPN provider:";
        lblVpnProvider.TextAlign = ContentAlignment.MiddleLeft;
        cboVpnProvider.DropDownStyle        = ComboBoxStyle.DropDownList;
        cboVpnProvider.Location             = new Point(148, 82);
        cboVpnProvider.Name                 = "cboVpnProvider";
        cboVpnProvider.Size                 = new Size(200, 23);
        cboVpnProvider.TabIndex             = 6;
        cboVpnProvider.SelectedIndexChanged += cboVpnProvider_SelectedIndexChanged;
        lblNatPmpAdapter.Location  = new Point(12, 111);
        lblNatPmpAdapter.Name      = "lblNatPmpAdapter";
        lblNatPmpAdapter.Size      = new Size(130, 23);
        lblNatPmpAdapter.TabIndex  = 7;
        lblNatPmpAdapter.Text      = "NAT-PMP adapter:";
        lblNatPmpAdapter.TextAlign = ContentAlignment.MiddleLeft;
        cboNatPmpAdapter.DropDownStyle = ComboBoxStyle.DropDownList;
        cboNatPmpAdapter.Location      = new Point(148, 111);
        cboNatPmpAdapter.Name          = "cboNatPmpAdapter";
        cboNatPmpAdapter.Size          = new Size(290, 23);
        cboNatPmpAdapter.TabIndex      = 8;
        btnRefreshAdapters.Enabled  = false;
        btnRefreshAdapters.Location = new Point(442, 111);
        btnRefreshAdapters.Name     = "btnRefreshAdapters";
        btnRefreshAdapters.Size     = new Size(26, 23);
        btnRefreshAdapters.TabIndex = 9;
        btnRefreshAdapters.Text     = "↻";
        btnRefreshAdapters.Click   += btnRefreshAdapters_Click;
        // Notify and show-update rows follow immediately after the NAT-PMP row at 29px spacing
        chkNotifyOnPortUpdate.AutoSize  = true;
        chkNotifyOnPortUpdate.Location  = new Point(12, 140);
        chkNotifyOnPortUpdate.Name      = "chkNotifyOnPortUpdate";
        chkNotifyOnPortUpdate.TabIndex  = 10;
        chkNotifyOnPortUpdate.Text      = "Show notification when port updates";
        chkShowUpdateForm.AutoSize      = true;
        chkShowUpdateForm.Location      = new Point(12, 169);
        chkShowUpdateForm.Name          = "chkShowUpdateForm";
        chkShowUpdateForm.TabIndex      = 11;
        chkShowUpdateForm.Text          = "Show update form on startup";
        // grpAutoRecovery sits at the bottom of grpGeneral.
        // All checkboxes at the same indent; "Trigger after" sub-rows indent one level (x=28).
        // Numeric fields align at x=148 and unit labels at x=204 - 24px row spacing throughout.
        grpAutoRecovery.Controls.Add(chkVerifyPort);
        grpAutoRecovery.Controls.Add(chkPortClosedRecovery);
        grpAutoRecovery.Controls.Add(lblPortClosedCycles);
        grpAutoRecovery.Controls.Add(nudPortClosedCycles);
        grpAutoRecovery.Controls.Add(lblPortClosedCyclesUnit);
        grpAutoRecovery.Controls.Add(chkAutoRecovery);
        grpAutoRecovery.Controls.Add(lblRecoveryCycles);
        grpAutoRecovery.Controls.Add(nudRecoveryCycles);
        grpAutoRecovery.Controls.Add(lblRecoveryCyclesUnit);
        grpAutoRecovery.Location = new Point(8, 196);
        grpAutoRecovery.Name     = "grpAutoRecovery";
        grpAutoRecovery.Size     = new Size(470, 150);
        grpAutoRecovery.TabIndex = 12;
        grpAutoRecovery.TabStop  = false;
        grpAutoRecovery.Text     = "Auto-recovery";
        chkVerifyPort.AutoSize        = true;
        chkVerifyPort.Location        = new Point(10, 20);
        chkVerifyPort.Name            = "chkVerifyPort";
        chkVerifyPort.TabIndex        = 0;
        chkVerifyPort.Text            = "Verify port after sync";
        chkVerifyPort.CheckedChanged += chkVerifyPort_CheckedChanged;
        chkPortClosedRecovery.AutoSize       = true;
        chkPortClosedRecovery.Location       = new Point(10, 44);
        chkPortClosedRecovery.Name           = "chkPortClosedRecovery";
        chkPortClosedRecovery.TabIndex       = 1;
        chkPortClosedRecovery.Text           = "Trigger auto-recovery when port stays closed";
        chkPortClosedRecovery.CheckedChanged += chkPortClosedRecovery_CheckedChanged;
        lblPortClosedCycles.Location  = new Point(28, 68);
        lblPortClosedCycles.Name      = "lblPortClosedCycles";
        lblPortClosedCycles.Size      = new Size(114, 23);
        lblPortClosedCycles.TabIndex  = 2;
        lblPortClosedCycles.Text      = "Trigger after";
        lblPortClosedCycles.TextAlign = ContentAlignment.MiddleLeft;
        nudPortClosedCycles.Location = new Point(148, 68);
        nudPortClosedCycles.Maximum  = new decimal(new int[] { 10, 0, 0, 0 });
        nudPortClosedCycles.Minimum  = new decimal(new int[] { 1, 0, 0, 0 });
        nudPortClosedCycles.Name     = "nudPortClosedCycles";
        nudPortClosedCycles.Size     = new Size(50, 23);
        nudPortClosedCycles.TabIndex = 3;
        nudPortClosedCycles.Value    = new decimal(new int[] { 3, 0, 0, 0 });
        lblPortClosedCyclesUnit.Location  = new Point(204, 68);
        lblPortClosedCyclesUnit.Name      = "lblPortClosedCyclesUnit";
        lblPortClosedCyclesUnit.Size      = new Size(240, 23);
        lblPortClosedCyclesUnit.TabIndex  = 4;
        lblPortClosedCyclesUnit.Text      = "confirmed closed checks";
        lblPortClosedCyclesUnit.TextAlign = ContentAlignment.MiddleLeft;
        chkAutoRecovery.AutoSize       = true;
        chkAutoRecovery.Location       = new Point(10, 96);
        chkAutoRecovery.Name           = "chkAutoRecovery";
        chkAutoRecovery.TabIndex       = 5;
        chkAutoRecovery.Text           = "Trigger auto-recovery when no port assigned or disconnected";
        chkAutoRecovery.CheckedChanged += chkAutoRecovery_CheckedChanged;
        lblRecoveryCycles.Location  = new Point(28, 120);
        lblRecoveryCycles.Name      = "lblRecoveryCycles";
        lblRecoveryCycles.Size      = new Size(114, 23);
        lblRecoveryCycles.TabIndex  = 6;
        lblRecoveryCycles.Text      = "Trigger after";
        lblRecoveryCycles.TextAlign = ContentAlignment.MiddleLeft;
        nudRecoveryCycles.Location = new Point(148, 120);
        nudRecoveryCycles.Maximum  = new decimal(new int[] { 10, 0, 0, 0 });
        nudRecoveryCycles.Minimum  = new decimal(new int[] { 1, 0, 0, 0 });
        nudRecoveryCycles.Name     = "nudRecoveryCycles";
        nudRecoveryCycles.Size     = new Size(50, 23);
        nudRecoveryCycles.TabIndex = 7;
        nudRecoveryCycles.Value    = new decimal(new int[] { 3, 0, 0, 0 });
        lblRecoveryCyclesUnit.Location  = new Point(204, 120);
        lblRecoveryCyclesUnit.Name      = "lblRecoveryCyclesUnit";
        lblRecoveryCyclesUnit.Size      = new Size(240, 23);
        lblRecoveryCyclesUnit.TabIndex  = 8;
        lblRecoveryCyclesUnit.Text      = "consecutive failed cycles";
        lblRecoveryCyclesUnit.TextAlign = ContentAlignment.MiddleLeft;
        // ── grpQBittorrent ────────────────────────────────────────────
        grpQBittorrent.Controls.Add(lblQBittorrentURL);
        grpQBittorrent.Controls.Add(txtQBittorrentURL);
        grpQBittorrent.Controls.Add(lblQBittorrentUserName);
        grpQBittorrent.Controls.Add(txtQBittorrentUserName);
        grpQBittorrent.Controls.Add(lblQBittorrentPassword);
        grpQBittorrent.Controls.Add(txtQBittorrentPassword);
        grpQBittorrent.Controls.Add(lblQBittorrentExePath);
        grpQBittorrent.Controls.Add(txtQBittorrentExePath);
        grpQBittorrent.Controls.Add(btnBrowseExePath);
        grpQBittorrent.Controls.Add(btnTestQBittorrent);
        grpQBittorrent.Controls.Add(lblQBittorrentProcessName);
        grpQBittorrent.Controls.Add(txtQBittorrentProcessName);
        grpQBittorrent.Controls.Add(chkRestartQBittorrent);
        grpQBittorrent.Controls.Add(chkForceStartQBittorrent);
        grpQBittorrent.Controls.Add(lblDefaultPort);
        grpQBittorrent.Controls.Add(nudDefaultPort);
        grpQBittorrent.Controls.Add(chkWarnOnInterfaceMismatch);
        grpQBittorrent.Controls.Add(chkRestartOnDisconnect);
        grpQBittorrent.Location = new Point(6, 6);
        grpQBittorrent.Name     = "grpQBittorrent";
        grpQBittorrent.Size     = new Size(488, 352);
        grpQBittorrent.TabIndex = 1;
        grpQBittorrent.TabStop  = false;
        grpQBittorrent.Text     = "qBittorrent";
        lblQBittorrentURL.Location  = new Point(12, 24);
        lblQBittorrentURL.Name      = "lblQBittorrentURL";
        lblQBittorrentURL.Size      = new Size(130, 23);
        lblQBittorrentURL.TabIndex  = 0;
        lblQBittorrentURL.Text      = "URL:";
        lblQBittorrentURL.TextAlign = ContentAlignment.MiddleLeft;
        txtQBittorrentURL.Location = new Point(148, 24);
        txtQBittorrentURL.Name     = "txtQBittorrentURL";
        txtQBittorrentURL.Size     = new Size(244, 23);
        txtQBittorrentURL.TabIndex = 1;
        btnTestQBittorrent.Location = new Point(398, 24);
        btnTestQBittorrent.Name     = "btnTestQBittorrent";
        btnTestQBittorrent.Size     = new Size(70, 23);
        btnTestQBittorrent.TabIndex = 2;
        btnTestQBittorrent.Text     = "Test";
        btnTestQBittorrent.Click   += btnTestQBittorrent_Click;
        lblQBittorrentUserName.Location  = new Point(12, 53);
        lblQBittorrentUserName.Name      = "lblQBittorrentUserName";
        lblQBittorrentUserName.Size      = new Size(130, 23);
        lblQBittorrentUserName.TabIndex  = 3;
        lblQBittorrentUserName.Text      = "Username:";
        lblQBittorrentUserName.TextAlign = ContentAlignment.MiddleLeft;
        txtQBittorrentUserName.Location = new Point(148, 53);
        txtQBittorrentUserName.Name     = "txtQBittorrentUserName";
        txtQBittorrentUserName.Size     = new Size(320, 23);
        txtQBittorrentUserName.TabIndex = 4;
        lblQBittorrentPassword.Location  = new Point(12, 82);
        lblQBittorrentPassword.Name      = "lblQBittorrentPassword";
        lblQBittorrentPassword.Size      = new Size(130, 23);
        lblQBittorrentPassword.TabIndex  = 5;
        lblQBittorrentPassword.Text      = "Password:";
        lblQBittorrentPassword.TextAlign = ContentAlignment.MiddleLeft;
        txtQBittorrentPassword.Location     = new Point(148, 82);
        txtQBittorrentPassword.Name         = "txtQBittorrentPassword";
        txtQBittorrentPassword.PasswordChar = '*';
        txtQBittorrentPassword.Size         = new Size(320, 23);
        txtQBittorrentPassword.TabIndex     = 6;
        lblQBittorrentExePath.Location  = new Point(12, 111);
        lblQBittorrentExePath.Name      = "lblQBittorrentExePath";
        lblQBittorrentExePath.Size      = new Size(130, 23);
        lblQBittorrentExePath.TabIndex  = 7;
        lblQBittorrentExePath.Text      = "Executable:";
        lblQBittorrentExePath.TextAlign = ContentAlignment.MiddleLeft;
        txtQBittorrentExePath.Location = new Point(148, 111);
        txtQBittorrentExePath.Name     = "txtQBittorrentExePath";
        txtQBittorrentExePath.Size     = new Size(276, 23);
        txtQBittorrentExePath.TabIndex = 8;
        btnBrowseExePath.Location = new Point(428, 111);
        btnBrowseExePath.Name     = "btnBrowseExePath";
        btnBrowseExePath.Size     = new Size(40, 23);
        btnBrowseExePath.TabIndex = 9;
        btnBrowseExePath.Text     = "...";
        btnBrowseExePath.Click   += btnBrowseExePath_Click;
        lblQBittorrentProcessName.Location  = new Point(12, 140);
        lblQBittorrentProcessName.Name      = "lblQBittorrentProcessName";
        lblQBittorrentProcessName.Size      = new Size(130, 23);
        lblQBittorrentProcessName.TabIndex  = 10;
        lblQBittorrentProcessName.Text      = "Process name:";
        lblQBittorrentProcessName.TextAlign = ContentAlignment.MiddleLeft;
        txtQBittorrentProcessName.Location = new Point(148, 140);
        txtQBittorrentProcessName.Name     = "txtQBittorrentProcessName";
        txtQBittorrentProcessName.Size     = new Size(320, 23);
        txtQBittorrentProcessName.TabIndex = 11;
        chkRestartQBittorrent.AutoSize  = true;
        chkRestartQBittorrent.Location  = new Point(12, 178);
        chkRestartQBittorrent.Name      = "chkRestartQBittorrent";
        chkRestartQBittorrent.Size      = new Size(314, 19);
        chkRestartQBittorrent.TabIndex  = 12;
        chkRestartQBittorrent.Text      = "Restart qBittorrent after a port change (recommended)";
        chkForceStartQBittorrent.AutoSize = true;
        chkForceStartQBittorrent.Location = new Point(12, 203);
        chkForceStartQBittorrent.Name     = "chkForceStartQBittorrent";
        chkForceStartQBittorrent.Size     = new Size(217, 19);
        chkForceStartQBittorrent.TabIndex = 13;
        chkForceStartQBittorrent.Text     = "Force start qBittorrent if not running";
        lblDefaultPort.Location  = new Point(12, 228);
        lblDefaultPort.Name      = "lblDefaultPort";
        lblDefaultPort.Size      = new Size(130, 23);
        lblDefaultPort.TabIndex  = 14;
        lblDefaultPort.Text      = "Default port:";
        lblDefaultPort.TextAlign = ContentAlignment.MiddleLeft;
        nudDefaultPort.Location = new Point(148, 228);
        nudDefaultPort.Maximum  = new decimal(new int[] { 65535, 0, 0, 0 });
        nudDefaultPort.Name     = "nudDefaultPort";
        nudDefaultPort.Size     = new Size(80, 23);
        nudDefaultPort.TabIndex = 15;
        chkWarnOnInterfaceMismatch.AutoSize = true;
        chkWarnOnInterfaceMismatch.Location = new Point(12, 257);
        chkWarnOnInterfaceMismatch.Name     = "chkWarnOnInterfaceMismatch";
        chkWarnOnInterfaceMismatch.Size     = new Size(306, 19);
        chkWarnOnInterfaceMismatch.TabIndex = 16;
        chkWarnOnInterfaceMismatch.Text     = "Warn when network interface doesn't match the VPN";
        chkRestartOnDisconnect.AutoSize = true;
        chkRestartOnDisconnect.Location = new Point(12, 282);
        chkRestartOnDisconnect.Name     = "chkRestartOnDisconnect";
        chkRestartOnDisconnect.Size     = new Size(295, 19);
        chkRestartOnDisconnect.TabIndex = 17;
        chkRestartOnDisconnect.Text     = "Restart qBittorrent if connection status disconnects";
        // ── grpDeluge ─────────────────────────────────────────────────
        grpDeluge.Controls.Add(lblDelugeURL);
        grpDeluge.Controls.Add(txtDelugeURL);
        grpDeluge.Controls.Add(lblDelugePassword);
        grpDeluge.Controls.Add(txtDelugePassword);
        grpDeluge.Controls.Add(lblDelugeExePath);
        grpDeluge.Controls.Add(txtDelugeExePath);
        grpDeluge.Controls.Add(btnBrowseDelugeExePath);
        grpDeluge.Controls.Add(btnTestDeluge);
        grpDeluge.Controls.Add(lblDelugeProcessName);
        grpDeluge.Controls.Add(txtDelugeProcessName);
        grpDeluge.Controls.Add(chkRestartDeluge);
        grpDeluge.Controls.Add(chkForceStartDeluge);
        grpDeluge.Controls.Add(lblDelugeDefaultPort);
        grpDeluge.Controls.Add(nudDelugeDefaultPort);
        grpDeluge.Location = new Point(6, 6);
        grpDeluge.Name     = "grpDeluge";
        grpDeluge.Size     = new Size(488, 352);
        grpDeluge.TabIndex = 3;
        grpDeluge.TabStop  = false;
        grpDeluge.Text     = "Deluge";
        grpDeluge.Visible  = false;
        lblDelugeURL.Location  = new Point(12, 24);
        lblDelugeURL.Name      = "lblDelugeURL";
        lblDelugeURL.Size      = new Size(130, 23);
        lblDelugeURL.TabIndex  = 0;
        lblDelugeURL.Text      = "URL:";
        lblDelugeURL.TextAlign = ContentAlignment.MiddleLeft;
        txtDelugeURL.Location = new Point(148, 24);
        txtDelugeURL.Name     = "txtDelugeURL";
        txtDelugeURL.Size     = new Size(244, 23);
        txtDelugeURL.TabIndex = 1;
        btnTestDeluge.Location = new Point(398, 24);
        btnTestDeluge.Name     = "btnTestDeluge";
        btnTestDeluge.Size     = new Size(70, 23);
        btnTestDeluge.TabIndex = 2;
        btnTestDeluge.Text     = "Test";
        btnTestDeluge.Click   += btnTestDeluge_Click;
        lblDelugePassword.Location  = new Point(12, 53);
        lblDelugePassword.Name      = "lblDelugePassword";
        lblDelugePassword.Size      = new Size(130, 23);
        lblDelugePassword.TabIndex  = 3;
        lblDelugePassword.Text      = "Password:";
        lblDelugePassword.TextAlign = ContentAlignment.MiddleLeft;
        txtDelugePassword.Location     = new Point(148, 53);
        txtDelugePassword.Name         = "txtDelugePassword";
        txtDelugePassword.PasswordChar = '*';
        txtDelugePassword.Size         = new Size(320, 23);
        txtDelugePassword.TabIndex     = 4;
        lblDelugeExePath.Location  = new Point(12, 82);
        lblDelugeExePath.Name      = "lblDelugeExePath";
        lblDelugeExePath.Size      = new Size(130, 23);
        lblDelugeExePath.TabIndex  = 5;
        lblDelugeExePath.Text      = "Executable:";
        lblDelugeExePath.TextAlign = ContentAlignment.MiddleLeft;
        txtDelugeExePath.Location = new Point(148, 82);
        txtDelugeExePath.Name     = "txtDelugeExePath";
        txtDelugeExePath.Size     = new Size(276, 23);
        txtDelugeExePath.TabIndex = 6;
        btnBrowseDelugeExePath.Location = new Point(428, 82);
        btnBrowseDelugeExePath.Name     = "btnBrowseDelugeExePath";
        btnBrowseDelugeExePath.Size     = new Size(40, 23);
        btnBrowseDelugeExePath.TabIndex = 7;
        btnBrowseDelugeExePath.Text     = "...";
        btnBrowseDelugeExePath.Click   += btnBrowseDelugeExePath_Click;
        lblDelugeProcessName.Location  = new Point(12, 111);
        lblDelugeProcessName.Name      = "lblDelugeProcessName";
        lblDelugeProcessName.Size      = new Size(130, 23);
        lblDelugeProcessName.TabIndex  = 8;
        lblDelugeProcessName.Text      = "Process name:";
        lblDelugeProcessName.TextAlign = ContentAlignment.MiddleLeft;
        txtDelugeProcessName.Location = new Point(148, 111);
        txtDelugeProcessName.Name     = "txtDelugeProcessName";
        txtDelugeProcessName.Size     = new Size(320, 23);
        txtDelugeProcessName.TabIndex = 9;
        chkRestartDeluge.AutoSize = true;
        chkRestartDeluge.Location = new Point(12, 149);
        chkRestartDeluge.Name     = "chkRestartDeluge";
        chkRestartDeluge.Size     = new Size(280, 19);
        chkRestartDeluge.TabIndex = 10;
        chkRestartDeluge.Text     = "Restart Deluge after a port change (recommended)";
        chkForceStartDeluge.AutoSize = true;
        chkForceStartDeluge.Location = new Point(12, 174);
        chkForceStartDeluge.Name     = "chkForceStartDeluge";
        chkForceStartDeluge.Size     = new Size(204, 19);
        chkForceStartDeluge.TabIndex = 11;
        chkForceStartDeluge.Text     = "Force start Deluge if not running";
        lblDelugeDefaultPort.Location  = new Point(12, 203);
        lblDelugeDefaultPort.Name      = "lblDelugeDefaultPort";
        lblDelugeDefaultPort.Size      = new Size(130, 23);
        lblDelugeDefaultPort.TabIndex  = 12;
        lblDelugeDefaultPort.Text      = "Default port:";
        lblDelugeDefaultPort.TextAlign = ContentAlignment.MiddleLeft;
        nudDelugeDefaultPort.Location = new Point(148, 203);
        nudDelugeDefaultPort.Maximum  = new decimal(new int[] { 65535, 0, 0, 0 });
        nudDelugeDefaultPort.Name     = "nudDelugeDefaultPort";
        nudDelugeDefaultPort.Size     = new Size(80, 23);
        nudDelugeDefaultPort.TabIndex = 13;
        // ── grpTransmission ───────────────────────────────────────────
        grpTransmission.Controls.Add(lblTransmissionURL);
        grpTransmission.Controls.Add(txtTransmissionURL);
        grpTransmission.Controls.Add(lblTransmissionUserName);
        grpTransmission.Controls.Add(txtTransmissionUserName);
        grpTransmission.Controls.Add(lblTransmissionPassword);
        grpTransmission.Controls.Add(txtTransmissionPassword);
        grpTransmission.Controls.Add(lblTransmissionExePath);
        grpTransmission.Controls.Add(txtTransmissionExePath);
        grpTransmission.Controls.Add(btnBrowseTransmissionExePath);
        grpTransmission.Controls.Add(btnTestTransmission);
        grpTransmission.Controls.Add(lblTransmissionProcessName);
        grpTransmission.Controls.Add(txtTransmissionProcessName);
        grpTransmission.Controls.Add(chkRestartTransmission);
        grpTransmission.Controls.Add(chkForceStartTransmission);
        grpTransmission.Controls.Add(lblTransmissionDefaultPort);
        grpTransmission.Controls.Add(nudTransmissionDefaultPort);
        grpTransmission.Location = new Point(6, 6);
        grpTransmission.Name     = "grpTransmission";
        grpTransmission.Size     = new Size(488, 352);
        grpTransmission.TabIndex = 2;
        grpTransmission.TabStop  = false;
        grpTransmission.Text     = "Transmission";
        grpTransmission.Visible  = false;
        lblTransmissionURL.Location  = new Point(12, 24);
        lblTransmissionURL.Name      = "lblTransmissionURL";
        lblTransmissionURL.Size      = new Size(130, 23);
        lblTransmissionURL.TabIndex  = 0;
        lblTransmissionURL.Text      = "URL:";
        lblTransmissionURL.TextAlign = ContentAlignment.MiddleLeft;
        txtTransmissionURL.Location = new Point(148, 24);
        txtTransmissionURL.Name     = "txtTransmissionURL";
        txtTransmissionURL.Size     = new Size(244, 23);
        txtTransmissionURL.TabIndex = 1;
        btnTestTransmission.Location = new Point(398, 24);
        btnTestTransmission.Name     = "btnTestTransmission";
        btnTestTransmission.Size     = new Size(70, 23);
        btnTestTransmission.TabIndex = 2;
        btnTestTransmission.Text     = "Test";
        btnTestTransmission.Click   += btnTestTransmission_Click;
        lblTransmissionUserName.Location  = new Point(12, 53);
        lblTransmissionUserName.Name      = "lblTransmissionUserName";
        lblTransmissionUserName.Size      = new Size(130, 23);
        lblTransmissionUserName.TabIndex  = 3;
        lblTransmissionUserName.Text      = "Username:";
        lblTransmissionUserName.TextAlign = ContentAlignment.MiddleLeft;
        txtTransmissionUserName.Location = new Point(148, 53);
        txtTransmissionUserName.Name     = "txtTransmissionUserName";
        txtTransmissionUserName.Size     = new Size(320, 23);
        txtTransmissionUserName.TabIndex = 4;
        lblTransmissionPassword.Location  = new Point(12, 82);
        lblTransmissionPassword.Name      = "lblTransmissionPassword";
        lblTransmissionPassword.Size      = new Size(130, 23);
        lblTransmissionPassword.TabIndex  = 5;
        lblTransmissionPassword.Text      = "Password:";
        lblTransmissionPassword.TextAlign = ContentAlignment.MiddleLeft;
        txtTransmissionPassword.Location     = new Point(148, 82);
        txtTransmissionPassword.Name         = "txtTransmissionPassword";
        txtTransmissionPassword.PasswordChar = '*';
        txtTransmissionPassword.Size         = new Size(320, 23);
        txtTransmissionPassword.TabIndex     = 6;
        lblTransmissionExePath.Location  = new Point(12, 111);
        lblTransmissionExePath.Name      = "lblTransmissionExePath";
        lblTransmissionExePath.Size      = new Size(130, 23);
        lblTransmissionExePath.TabIndex  = 7;
        lblTransmissionExePath.Text      = "Executable:";
        lblTransmissionExePath.TextAlign = ContentAlignment.MiddleLeft;
        txtTransmissionExePath.Location = new Point(148, 111);
        txtTransmissionExePath.Name     = "txtTransmissionExePath";
        txtTransmissionExePath.Size     = new Size(276, 23);
        txtTransmissionExePath.TabIndex = 8;
        btnBrowseTransmissionExePath.Location = new Point(428, 111);
        btnBrowseTransmissionExePath.Name     = "btnBrowseTransmissionExePath";
        btnBrowseTransmissionExePath.Size     = new Size(40, 23);
        btnBrowseTransmissionExePath.TabIndex = 9;
        btnBrowseTransmissionExePath.Text     = "...";
        btnBrowseTransmissionExePath.Click   += btnBrowseTransmissionExePath_Click;
        lblTransmissionProcessName.Location  = new Point(12, 140);
        lblTransmissionProcessName.Name      = "lblTransmissionProcessName";
        lblTransmissionProcessName.Size      = new Size(130, 23);
        lblTransmissionProcessName.TabIndex  = 10;
        lblTransmissionProcessName.Text      = "Process name:";
        lblTransmissionProcessName.TextAlign = ContentAlignment.MiddleLeft;
        txtTransmissionProcessName.Location = new Point(148, 140);
        txtTransmissionProcessName.Name     = "txtTransmissionProcessName";
        txtTransmissionProcessName.Size     = new Size(320, 23);
        txtTransmissionProcessName.TabIndex = 11;
        chkRestartTransmission.AutoSize  = true;
        chkRestartTransmission.Location  = new Point(12, 178);
        chkRestartTransmission.Name      = "chkRestartTransmission";
        chkRestartTransmission.Size      = new Size(305, 19);
        chkRestartTransmission.TabIndex  = 12;
        chkRestartTransmission.Text      = "Restart Transmission after a port change (recommended)";
        chkForceStartTransmission.AutoSize = true;
        chkForceStartTransmission.Location = new Point(12, 203);
        chkForceStartTransmission.Name     = "chkForceStartTransmission";
        chkForceStartTransmission.Size     = new Size(214, 19);
        chkForceStartTransmission.TabIndex = 13;
        chkForceStartTransmission.Text     = "Force start Transmission if not running";
        lblTransmissionDefaultPort.Location  = new Point(12, 232);
        lblTransmissionDefaultPort.Name      = "lblTransmissionDefaultPort";
        lblTransmissionDefaultPort.Size      = new Size(130, 23);
        lblTransmissionDefaultPort.TabIndex  = 14;
        lblTransmissionDefaultPort.Text      = "Default port:";
        lblTransmissionDefaultPort.TextAlign = ContentAlignment.MiddleLeft;
        nudTransmissionDefaultPort.Location = new Point(148, 232);
        nudTransmissionDefaultPort.Maximum  = new decimal(new int[] { 65535, 0, 0, 0 });
        nudTransmissionDefaultPort.Name     = "nudTransmissionDefaultPort";
        nudTransmissionDefaultPort.Size     = new Size(80, 23);
        nudTransmissionDefaultPort.TabIndex = 15;
        // ── grpExtra ──────────────────────────────────────────────────
        grpExtra.Controls.Add(lblColorTheme);
        grpExtra.Controls.Add(cboColorTheme);
        grpExtra.Controls.Add(lblPostUpdateCmd);
        grpExtra.Controls.Add(txtPostUpdateCmd);
        grpExtra.Controls.Add(chkDebugMode);
        grpExtra.Location = new Point(6, 6);
        grpExtra.Name     = "grpExtra";
        grpExtra.Size     = new Size(488, 352);
        grpExtra.TabIndex = 4;
        grpExtra.TabStop  = false;
        grpExtra.Text     = "Extra";
        lblColorTheme.Location  = new Point(12, 24);
        lblColorTheme.Name      = "lblColorTheme";
        lblColorTheme.Size      = new Size(130, 23);
        lblColorTheme.TabIndex  = 0;
        lblColorTheme.Text      = "Color theme:";
        lblColorTheme.TextAlign = ContentAlignment.MiddleLeft;
        cboColorTheme.DropDownStyle = ComboBoxStyle.DropDownList;
        cboColorTheme.Location      = new Point(148, 24);
        cboColorTheme.Name          = "cboColorTheme";
        cboColorTheme.Size          = new Size(150, 23);
        cboColorTheme.TabIndex      = 1;
        lblPostUpdateCmd.Location  = new Point(12, 53);
        lblPostUpdateCmd.Name      = "lblPostUpdateCmd";
        lblPostUpdateCmd.Size      = new Size(130, 23);
        lblPostUpdateCmd.TabIndex  = 2;
        lblPostUpdateCmd.Text      = "Post-update:";
        lblPostUpdateCmd.TextAlign = ContentAlignment.MiddleLeft;
        txtPostUpdateCmd.Location = new Point(148, 53);
        txtPostUpdateCmd.Name     = "txtPostUpdateCmd";
        txtPostUpdateCmd.Size     = new Size(320, 23);
        txtPostUpdateCmd.TabIndex = 3;
        chkDebugMode.AutoSize = true;
        chkDebugMode.Location = new Point(12, 82);
        chkDebugMode.Name     = "chkDebugMode";
        chkDebugMode.Size     = new Size(142, 19);
        chkDebugMode.TabIndex = 4;
        chkDebugMode.Text     = "Enable debug logging";
        // ── tabSettings ───────────────────────────────────────────────
        // Tabs keep the dialog short enough for small screens (the single-column layout
        // outgrew a 1080p display at 125% scaling). The three client groups overlay each
        // other on the Client tab; their existing visibility toggling is unchanged.
        tabSettings.Controls.Add(tabGeneral);
        tabSettings.Controls.Add(tabClient);
        tabSettings.Controls.Add(tabExtra);
        tabSettings.ItemSize      = new Size(80, 28);
        tabSettings.Location      = new Point(6, 8);
        tabSettings.Name          = "tabSettings";
        tabSettings.SelectedIndex = 0;
        tabSettings.Size          = new Size(508, 403);
        tabSettings.TabIndex      = 0;
        // UseVisualStyleBackColor is deliberately left false on all pages: the visual-style
        // page background renders light even in dark mode, leaving a white band wherever the
        // group box does not cover the page. Default (Control color) follows the app theme.
        tabGeneral.Controls.Add(grpGeneral);
        tabGeneral.Name = "tabGeneral";
        tabGeneral.Text = "General";
        tabClient.Controls.Add(grpQBittorrent);
        tabClient.Controls.Add(grpDeluge);
        tabClient.Controls.Add(grpTransmission);
        tabClient.Name = "tabClient";
        tabClient.Text = "Client";
        tabExtra.Controls.Add(grpExtra);
        tabExtra.Name = "tabExtra";
        tabExtra.Text = "Extra";
        // ── Buttons ───────────────────────────────────────────────────
        btnOK.Location = new Point(340, 421);
        btnOK.Name     = "btnOK";
        btnOK.Size     = new Size(82, 28);
        btnOK.TabIndex = 1;
        btnOK.Text     = "OK";
        btnOK.Click   += btnOK_Click;
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Location     = new Point(430, 421);
        btnCancel.Name         = "btnCancel";
        btnCancel.Size         = new Size(82, 28);
        btnCancel.TabIndex     = 2;
        btnCancel.Text         = "Cancel";
        btnCancel.Click       += btnCancel_Click;
        // ── SettingsForm ──────────────────────────────────────────────
        AcceptButton        = btnOK;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode       = AutoScaleMode.Font;
        CancelButton        = btnCancel;
        ClientSize          = new Size(520, 457);
        Controls.Add(tabSettings);
        Controls.Add(btnOK);
        Controls.Add(btnCancel);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox     = false;
        MinimizeBox     = false;
        Name            = "SettingsForm";
        ShowIcon        = false;
        ShowInTaskbar   = false;
        StartPosition   = FormStartPosition.CenterScreen;
        Text            = "qbPortWeaver | Settings";
        grpGeneral.ResumeLayout(false);
        grpGeneral.PerformLayout();
        grpAutoRecovery.ResumeLayout(false);
        grpAutoRecovery.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudUpdateInterval).EndInit();
        ((System.ComponentModel.ISupportInitialize)nudRecoveryCycles).EndInit();
        ((System.ComponentModel.ISupportInitialize)nudPortClosedCycles).EndInit();
        grpQBittorrent.ResumeLayout(false);
        grpQBittorrent.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudDefaultPort).EndInit();
        grpDeluge.ResumeLayout(false);
        grpDeluge.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudDelugeDefaultPort).EndInit();
        grpTransmission.ResumeLayout(false);
        grpTransmission.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)nudTransmissionDefaultPort).EndInit();
        grpExtra.ResumeLayout(false);
        grpExtra.PerformLayout();
        tabGeneral.ResumeLayout(false);
        tabClient.ResumeLayout(false);
        tabExtra.ResumeLayout(false);
        tabSettings.ResumeLayout(false);
        ResumeLayout(false);
    }

    private TabControl    tabSettings;
    private TabPage       tabGeneral;
    private TabPage       tabClient;
    private TabPage       tabExtra;

    private GroupBox      grpGeneral;
    private Label         lblBitTorrentClient;
    private ComboBox      cboBitTorrentClient;
    private Label         lblUpdateInterval;
    private NumericUpDown nudUpdateInterval;
    private Label         lblSeconds;
    private Label         lblVpnProvider;
    private ComboBox      cboVpnProvider;
    private Label         lblNatPmpAdapter;
    private ComboBox      cboNatPmpAdapter;
    private Button        btnRefreshAdapters;
    private CheckBox      chkNotifyOnPortUpdate;
    private CheckBox      chkShowUpdateForm;
    private GroupBox      grpAutoRecovery;
    private CheckBox      chkVerifyPort;
    private CheckBox      chkPortClosedRecovery;
    private Label         lblPortClosedCycles;
    private NumericUpDown nudPortClosedCycles;
    private Label         lblPortClosedCyclesUnit;
    private CheckBox      chkAutoRecovery;
    private Label         lblRecoveryCycles;
    private NumericUpDown nudRecoveryCycles;
    private Label         lblRecoveryCyclesUnit;

    private GroupBox      grpQBittorrent;
    private Label         lblQBittorrentURL;
    private TextBox       txtQBittorrentURL;
    private Label         lblQBittorrentUserName;
    private TextBox       txtQBittorrentUserName;
    private Label         lblQBittorrentPassword;
    private TextBox       txtQBittorrentPassword;
    private Label         lblQBittorrentExePath;
    private TextBox       txtQBittorrentExePath;
    private Button        btnBrowseExePath;
    private Button        btnTestQBittorrent;
    private Label         lblQBittorrentProcessName;
    private TextBox       txtQBittorrentProcessName;
    private CheckBox      chkRestartQBittorrent;
    private CheckBox      chkForceStartQBittorrent;
    private Label         lblDefaultPort;
    private NumericUpDown nudDefaultPort;
    private CheckBox      chkWarnOnInterfaceMismatch;
    private CheckBox      chkRestartOnDisconnect;

    private GroupBox      grpDeluge;
    private Label         lblDelugeURL;
    private TextBox       txtDelugeURL;
    private Label         lblDelugePassword;
    private TextBox       txtDelugePassword;
    private Label         lblDelugeExePath;
    private TextBox       txtDelugeExePath;
    private Button        btnBrowseDelugeExePath;
    private Button        btnTestDeluge;
    private Label         lblDelugeProcessName;
    private TextBox       txtDelugeProcessName;
    private CheckBox      chkRestartDeluge;
    private CheckBox      chkForceStartDeluge;
    private Label         lblDelugeDefaultPort;
    private NumericUpDown nudDelugeDefaultPort;

    private GroupBox      grpTransmission;
    private Label         lblTransmissionURL;
    private TextBox       txtTransmissionURL;
    private Label         lblTransmissionUserName;
    private TextBox       txtTransmissionUserName;
    private Label         lblTransmissionPassword;
    private TextBox       txtTransmissionPassword;
    private Label         lblTransmissionExePath;
    private TextBox       txtTransmissionExePath;
    private Button        btnBrowseTransmissionExePath;
    private Button        btnTestTransmission;
    private Label         lblTransmissionProcessName;
    private TextBox       txtTransmissionProcessName;
    private CheckBox      chkRestartTransmission;
    private CheckBox      chkForceStartTransmission;
    private Label         lblTransmissionDefaultPort;
    private NumericUpDown nudTransmissionDefaultPort;

    private GroupBox      grpExtra;
    private Label         lblColorTheme;
    private ComboBox      cboColorTheme;
    private Label         lblPostUpdateCmd;
    private TextBox       txtPostUpdateCmd;
    private CheckBox      chkDebugMode;

    private Button        btnOK;
    private Button        btnCancel;
    private ToolTip       toolTip;
}
