; Script generated by the HM NIS Edit Script Wizard.

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "qbPortWeaver"
; PRODUCT_VERSION can be overridden at compile time with:
;   makensis /DPRODUCT_VERSION=x.y.z qbPortWeaverSetup.nsi
!ifndef PRODUCT_VERSION
  !define PRODUCT_VERSION "2.2.0"
!endif
!define PRODUCT_PUBLISHER "@martsg666"
!define PRODUCT_WEB_SITE "https://github.com/martsg666/qbPortWeaver"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"
!include "nsDialogs.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "..\qbPortWeaver.ico"
!define MUI_UNICON "..\qbPortWeaver.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Post-install notice page
Page custom PostInstallNotice
!define MUI_FINISHPAGE_RUN "$INSTDIR\\${PRODUCT_NAME}.exe"
; Finish page
!insertmacro MUI_PAGE_FINISH
; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES
; Language files
!insertmacro MUI_LANGUAGE "English"
; MUI end ------

; Require administrator rights — needed to install to $PROGRAMFILES64
RequestExecutionLevel admin

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "${PRODUCT_NAME}_${PRODUCT_VERSION}_Setup.exe"
InstallDir "$PROGRAMFILES64\${PRODUCT_NAME}"
ShowInstDetails show
ShowUnInstDetails show

Function .onInit

  ; Check for previously installed version.
  ReadRegStr $R0 HKLM "${PRODUCT_UNINST_KEY}" "UninstallString"
  StrCmp $R0 "" Done
  
  MessageBox MB_OKCANCEL|MB_ICONEXCLAMATION \
  "${PRODUCT_NAME} is already installed. $\n$\nYou must uninstall the currently installed version before installing this upgrade. $\n$\nDo you want to start the uninstaller?" \
  IDOK UninstallPrevious
  Abort

; Run the uninstaller.
UninstallPrevious:
  ClearErrors
  ; Run the uninstaller
  ExecWait '$R0 _?=$INSTDIR'
  
Done:

FunctionEnd

Function PostInstallNotice
  nsDialogs::Create 1018
  Pop $0

  ${NSD_CreateLabel} 0 0 100% 200u "\
Installation completed successfully.$\r$\n\
$\r$\n\
To configure the application, right-click the tray icon and select Settings."

  Pop $0
  nsDialogs::Show
FunctionEnd

Section "MainSection" SEC01

  ; Kill qbPortWeaver if running
  ExecWait 'cmd /c taskkill /F /IM ${PRODUCT_NAME}.exe'

  SetOutPath "$INSTDIR"
  SetOverwrite on
  SetRebootFlag false
  File "..\bin\Release\net10.0-windows\win-x64\publish\qbPortWeaver.exe"
  File "..\README.md"
  
  CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
  CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"
  CreateShortCut "$DESKTOP\${PRODUCT_NAME}.lnk" "$INSTDIR\${PRODUCT_NAME}.exe"

SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\uninst.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\uninst.exe"
  WriteRegDword ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoRepair" "1"
  WriteRegDword ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoModify" "1"
SectionEnd

Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer."
FunctionEnd

Function un.onInit
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" IDYES +2
  Abort
FunctionEnd

Section Uninstall

  ; Kill qbPortWeaver if running
  ExecWait 'cmd /c taskkill /F /IM ${PRODUCT_NAME}.exe'

  RMDir /r "$INSTDIR"

  Delete "$DESKTOP\${PRODUCT_NAME}.lnk"
  Delete "$SMPROGRAMS\${PRODUCT_NAME}\${PRODUCT_NAME}.lnk"
  RMDir "$SMPROGRAMS\${PRODUCT_NAME}"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  SetAutoClose true

SectionEnd